dist: trusty
sudo: required
language: php

php:
  - 7.1.3
  - 7.2
  - Nightly

services:
  - postgresql


install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
